### ISSUE TITLE
Does zforth support more memory than 16Kb

### ISSUE THREAD

**Issue by pszym3** [zevv/zForth#40] opened 2024-04-18 21:51 UTC
Hi :)
ZForth - Great job

However, I have a problem. Does zforth support more memory than 16Kb? I did a test and after exceeding the 16Kb limit, the words stop working properly. Please test:

#define ZF_DICT_SIZE 65536 ( zfconf.h )

20000 h ! (set core.zf somewhere at the beginning after the word "!" )
include core.zf (it throws errors)

Can you check this?

Thank you very much and sorry for my poor English. Regards

**Comment by zevv** [comment] 2024-04-21 19:21
Ah, that's a funny one. The problem has to do with the variable length encoding of words in zforth, I always expected this to come back and bite me one day, and here it is.

The snatch is in the definition of the `if` word: here a conditional is compiled, followed by a jump for which the address is not yet known, so here a temporary value of `999` is used as a placeholder. Then the conditional code is added, and the `fi` word fills in the address that was written first, overwriting the `999`.

The problem is that the encoding of values on the dictionary uses variable length, depending on the magnitude of the number. Any number up to 128 fits in 1 bytes, up to 16383 in two bytes, and anything other that that uses the native C cell size. The placeholder value `999` fits in the two byte format, so 2 bytes are reserved here. But when the `here` value is larger than 16383, the `fi` word will overwrite the address with the actual jump target, which will then take more then 2 bytes, effectively corrupting the dictionary. Boom.

A workaround for you for now is to change the `999` values in `core.zf` to `16384`.

I'm not sure if that will solve all issues, I'll have to go through the code to see if there are more potential problems hiding here.

Ideally zforth would need a way to indicate that a store should always use the native format for specific values like jump targets.

**Comment by pszym3** [comment] 2024-04-21 20:21
Thank you very much for your quick response and dealing with this topic. I created a graphics library and turtle graphics (linux) in zforth. It would be nice to have a little more memory.

**Comment by zevv** [comment] 2024-04-21 20:28
> Thank you very much for your quick response and dealing with this topic. I created a graphics library and turtle graphics (linux) in zforth. It would be nice to have a little more memory.


Sure, my plan is to come up with a proper fix, hopefully somewhere over the next days I can find some time on this.

**Comment by zevv** [comment] 2024-04-22 08:58
Just pushed a fix; let me know if this works for you!

**Comment by pszym3** [comment] 2024-04-22 16:11
Yes! I can confirm that this fix works very well for me. Thank you :)

**Closed** 2024-04-23 12:52 UTC
